#!/usr/bin/env bash
#
# Install or update the self-hosted HoneySentinel stack on this machine.
#
#   sudo bash deploy/server/install.sh
#
# Expects the repository at /opt/honeysentinel. Safe to re-run: secrets,
# certificates and the admin account are created once and then left alone;
# images are rebuilt and containers recreated only where something changed.
#
# What it does:
#   1. generates .env (database password, JWT/encryption keys, ingest token)
#   2. issues a self-signed TLS certificate for Postgres
#   3. fetches the DB-IP City Lite geolocation database (no account needed)
#   4. installs the egress firewall and nightly backup as systemd units
#   5. builds and starts the stack
#   6. creates the administrator, without any synthetic data
#   7. publishes the dashboard on the tailnet with Tailscale Serve (HTTPS)

set -euo pipefail

[[ $EUID -eq 0 ]] || { echo "Run with sudo." >&2; exit 1; }

HERE="$(cd "$(dirname "$0")" && pwd)"
cd "$HERE"
STATE="$HERE/state"
ENV_FILE="$HERE/.env"
WEB_PORT=8088

[[ "$HERE" == /opt/honeysentinel/deploy/server ]] || {
  echo "Expected the repository at /opt/honeysentinel (the systemd units point there)." >&2
  exit 1
}

install -d -m 0700 "$STATE"

rand() { python3 -c "import secrets; print(secrets.token_urlsafe(48))"; }

echo "==> 1/7  Secrets"
if [[ ! -f "$ENV_FILE" ]]; then
  dns_name=$(tailscale status --json | python3 -c 'import json,sys; print(json.load(sys.stdin)["Self"]["DNSName"].rstrip("."))')
  public_ip=$(curl -fsS -m 10 https://api.ipify.org || true)
  umask 077
  cat > "$ENV_FILE" <<EOF
# Generated by install.sh on $(date -u +%Y-%m-%dT%H:%MZ). Keep private.
# Changing ENCRYPTION_KEY makes every stored command and payload unreadable.
POSTGRES_PASSWORD=$(python3 -c "import secrets; print(secrets.token_hex(32))")
SECRET_KEY=$(rand)
ENCRYPTION_KEY=$(rand)
HONEYPOT_INGEST_TOKEN=$(rand)

DASHBOARD_ORIGIN=https://${dns_name}
WEB_PORT=${WEB_PORT}

# Name this engine registers under. Traffic you generate yourself must come
# from a separate engine named controlled-test-node, never this one.
HONEYPOT_NODE_NAME=honeysentinel-debian
# Advertised in FTP passive replies. Update if the ISP changes the address.
PUBLIC_IP=${public_ip}

VITE_GEOIP_ATTRIBUTION='<a href="https://db-ip.com">IP Geolocation by DB-IP</a>'

# Optional; the backend has no internet access on this host (see
# docker-compose.yml), so email and webhook alerts also need it attached to a
# network with egress before these do anything.
# SMTP_HOST=
# SMTP_USER=
# SMTP_PASSWORD=
# ALERT_EMAIL_FROM=
# ALERT_EMAIL_TO=
# WEBHOOK_URL=
# WEBHOOK_SECRET=
# CHIMERA_URL=
EOF
  echo "    wrote $ENV_FILE"
else
  echo "    $ENV_FILE exists; kept"
fi

echo "==> 2/7  TLS certificates"
tls="$STATE/pg-tls"
if [[ ! -f "$tls/server.key" ]]; then
  install -d -m 0755 "$tls"
  openssl req -x509 -newkey rsa:3072 -nodes -days 3650 -sha256 \
    -subj "/CN=postgres" -addext "subjectAltName=DNS:postgres" \
    -keyout "$tls/server.key" -out "$tls/server.crt" 2>/dev/null
  # uid/gid 70 is postgres in the postgres:16-alpine image.
  chown 70:70 "$tls/server.key" "$tls/server.crt"
  chmod 0600 "$tls/server.key"
  echo "    issued"
else
  echo "    exists; kept"
fi

# The HTTPS decoy otherwise generates a fresh certificate on every restart,
# and a certificate that keeps changing is itself a tell.
decoy_tls="$STATE/decoy-tls"
if [[ ! -f "$decoy_tls/server.key" ]]; then
  install -d -m 0755 "$decoy_tls"
  openssl req -x509 -newkey rsa:2048 -nodes -days 1095 -sha256 \
    -subj "/CN=web-server-01" -addext "subjectAltName=DNS:web-server-01" \
    -keyout "$decoy_tls/server.key" -out "$decoy_tls/server.crt" 2>/dev/null
  # uid 10001 is the engine's user in honeypot/Dockerfile.
  chown 10001:10001 "$decoy_tls/server.key" "$decoy_tls/server.crt"
  chmod 0600 "$decoy_tls/server.key"
  echo "    issued the HTTPS decoy's certificate"
fi

echo "==> 3/7  GeoIP database (DB-IP City Lite, CC BY 4.0)"
geo="$STATE/geoip"
install -d -m 0755 "$geo"
if [[ ! -f "$geo/city.mmdb" ]] || [[ $(find "$geo/city.mmdb" -mtime +35 | wc -l) -gt 0 ]]; then
  ok=0
  # Published monthly; fall back a month in case this one is not out yet.
  for month in "$(date +%Y-%m)" "$(date -d '-1 month' +%Y-%m)"; do
    if curl -fsSL -m 300 "https://download.db-ip.com/free/dbip-city-lite-${month}.mmdb.gz" \
        -o "$geo/city.mmdb.gz.part"; then
      gunzip -c "$geo/city.mmdb.gz.part" > "$geo/city.mmdb.part"
      mv "$geo/city.mmdb.part" "$geo/city.mmdb"
      rm -f "$geo/city.mmdb.gz.part"
      chmod 0644 "$geo/city.mmdb"
      echo "    installed dbip-city-lite-${month}"
      ok=1
      break
    fi
  done
  [[ $ok -eq 1 ]] || echo "    download failed; sessions will have no location until it succeeds"
else
  echo "    current; kept"
fi

echo "==> 4/7  Egress firewall and backups"
install -m 0644 "$HERE/systemd/"honeysentinel-*.service "$HERE/systemd/"honeysentinel-*.timer /etc/systemd/system/
systemctl daemon-reload
systemctl enable honeysentinel-egress.service >/dev/null 2>&1
systemctl restart honeysentinel-egress.service
systemctl enable --now honeysentinel-backup.timer >/dev/null 2>&1
iptables -S DOCKER-USER | grep -q HS-DECOY-EGRESS \
  || { echo "    egress rules missing; refusing to expose the engine" >&2; exit 1; }
echo "    egress rules active; nightly backup scheduled"

echo "==> 5/7  Build and start"
docker compose up -d --build --remove-orphans

echo "    waiting for the API"
for _ in $(seq 1 90); do
  status=$(docker inspect -f '{{.State.Health.Status}}' "$(docker compose ps -q backend)" 2>/dev/null || true)
  [[ "$status" == healthy ]] && break
  sleep 2
done
[[ "$status" == healthy ]] || { echo "    backend did not become healthy" >&2; docker compose logs --tail 50 backend >&2; exit 1; }

echo "==> 6/7  Administrator"
creds="$STATE/admin-credentials"
if [[ ! -f "$creds" ]]; then
  admin_email=admin@honeysentinel.io
  admin_pass=$(python3 -c "import secrets; print(secrets.token_urlsafe(18))")
  docker compose exec -T -e ADMIN_EMAIL="$admin_email" -e ADMIN_PASSWORD="$admin_pass" \
    backend python - < "$HERE/create_admin.py"
  umask 077
  printf 'email=%s\npassword=%s\n' "$admin_email" "$admin_pass" > "$creds"
  echo "    credentials saved to $creds (root only)"
else
  echo "    exists; kept ($creds)"
fi

echo "==> 7/7  Tailscale Serve"
if timeout 20 tailscale serve --bg --https=443 "http://127.0.0.1:${WEB_PORT}"; then
  echo "    dashboard: $(grep ^DASHBOARD_ORIGIN "$ENV_FILE" | cut -d= -f2)"
else
  echo "    Serve is not enabled on the tailnet yet: approve the link above, then re-run."
fi

docker compose ps
