#!/usr/bin/env bash
#
# Install or update the self-hosted HoneySentinel stack on this machine.
#
#   sudo bash deploy/server/install.sh
#
# Expects the repository at /opt/honeysentinel. Safe to re-run: secrets,
# certificates and the admin account are created once and then left alone;
# images are rebuilt and containers recreated only where something changed.
#
# What it does:
#   1. generates .env (database password, JWT/encryption keys, ingest token)
#   2. issues a self-signed TLS certificate for Postgres
#   3. fetches the DB-IP City Lite geolocation database (no account needed)
#   4. installs the egress firewall and nightly backup as systemd units
#   5. builds and starts the stack
#   6. creates the administrator, without any synthetic data
#   7. publishes the dashboard on the tailnet with Tailscale Serve (HTTPS)

set -euo pipefail

[[ $EUID -eq 0 ]] || { echo "Run with sudo." >&2; exit 1; }

missing=()
for bin in docker python3 curl openssl iptables tailscale git; do
  command -v "$bin" >/dev/null 2>&1 || missing+=("$bin")
done
docker compose version >/dev/null 2>&1 || missing+=("docker-compose-plugin")
if [[ ${#missing[@]} -gt 0 ]]; then
  echo "Missing prerequisites: ${missing[*]}" >&2
  echo "On Debian: apt install docker.io docker-compose-plugin python3 curl openssl iptables git; Tailscale from https://tailscale.com/download" >&2
  exit 1
fi

HERE="$(cd "$(dirname "$0")" && pwd)"
cd "$HERE"
STATE="$HERE/state"
ENV_FILE="$HERE/.env"
WEB_PORT=8088
MODEL_FILE=wolfram-Q4_K_M.gguf
DECIDER_FILE=Kev-4B-Q8_0.gguf

[[ "$HERE" == /opt/honeysentinel/deploy/server ]] || {
  echo "Expected the repository at /opt/honeysentinel (the systemd units point there)." >&2
  exit 1
}

install -d -m 0700 "$STATE"

rand() { python3 -c "import secrets; print(secrets.token_urlsafe(48))"; }

echo "==> 1/7  Secrets"
if [[ ! -f "$ENV_FILE" ]]; then
  dns_name=$(tailscale status --json | python3 -c 'import json,sys; print(json.load(sys.stdin)["Self"]["DNSName"].rstrip("."))')
  public_ip=$(curl -fsS -m 10 https://api.ipify.org || true)
  umask 077
  cat > "$ENV_FILE" <<EOF
# Generated by install.sh on $(date -u +%Y-%m-%dT%H:%MZ). Keep private.
# Changing ENCRYPTION_KEY makes every stored command and payload unreadable.
POSTGRES_PASSWORD=$(python3 -c "import secrets; print(secrets.token_hex(32))")
SECRET_KEY=$(rand)
ENCRYPTION_KEY=$(rand)
HONEYPOT_INGEST_TOKEN=$(rand)

DASHBOARD_ORIGIN=https://${dns_name}
WEB_PORT=${WEB_PORT}

# Name this engine registers under. Traffic you generate yourself must come
# from a separate engine named controlled-test-node, never this one.
HONEYPOT_NODE_NAME=honeysentinel-debian
# Advertised in FTP passive replies. Update if the ISP changes the address.
PUBLIC_IP=${public_ip}

VITE_GEOIP_ATTRIBUTION='<a href="https://db-ip.com">IP Geolocation by DB-IP</a>'

# Optional; the backend has no internet access on this host (see
# docker-compose.yml), so email and webhook alerts also need it attached to a
# network with egress before these do anything.
# SMTP_HOST=
# SMTP_USER=
# SMTP_PASSWORD=
# ALERT_EMAIL_FROM=
# ALERT_EMAIL_TO=
# WEBHOOK_URL=
# WEBHOOK_SECRET=
# CHIMERA_URL=
EOF
  echo "    wrote $ENV_FILE"
else
  echo "    $ENV_FILE exists; kept"
fi
# Settings added by later versions are appended (commented, with their
# defaults) so an operator can find them without diffing the repository.
append_env() {
  grep -q "^#\? \?$1=" "$ENV_FILE" || printf '%s\n' "$2" >> "$ENV_FILE"
}
append_env ALERT_DEDUP_WINDOW_MINUTES "# ALERT_DEDUP_WINDOW_MINUTES=60   # repeats from one address fold into the open alert"
append_env ALERT_SUPPRESS_SCANNERS   "# ALERT_SUPPRESS_SCANNERS=true    # no alerts for Censys/Shodan/Shadowserver"
append_env SESSION_RETENTION_DAYS    "# SESSION_RETENTION_DAYS=0        # 0 keeps every session"
append_env AUDIT_RETENTION_DAYS      "# AUDIT_RETENTION_DAYS=365"
append_env WOLFRAM_THREADS           "# WOLFRAM_THREADS=6               # CPU threads for the analysis model"
append_env DECIDER_THREADS           "# DECIDER_THREADS=6               # CPU threads for the decision model"
append_env DECIDER_SKIP_THRESHOLD    "# DECIDER_SKIP_THRESHOLD=0.85     # triage skips the LLM above this p(information gathering at most)"
append_env DECIDER_DROP_UNCONFIRMED  "# DECIDER_DROP_UNCONFIRMED=false  # remove, not just mark, techniques the transcript does not support"
WEB_PORT=$(grep -E '^WEB_PORT=' "$ENV_FILE" | cut -d= -f2 | tr -d '[:space:]' || true)
WEB_PORT=${WEB_PORT:-8088}

if ! timedatectl show -p NTPSynchronized --value 2>/dev/null | grep -q yes; then
  echo "WARNING: the clock is not NTP-synchronised; authenticator codes and evidence timestamps depend on it (timedatectl set-ntp true)." >&2
fi

echo "==> 2/7  TLS certificates"
tls="$STATE/pg-tls"
if [[ ! -f "$tls/server.key" ]]; then
  install -d -m 0755 "$tls"
  openssl req -x509 -newkey rsa:3072 -nodes -days 3650 -sha256 \
    -subj "/CN=postgres" -addext "subjectAltName=DNS:postgres" \
    -keyout "$tls/server.key" -out "$tls/server.crt" 2>/dev/null
  # uid/gid 70 is postgres in the postgres:16-alpine image.
  chown 70:70 "$tls/server.key" "$tls/server.crt"
  chmod 0600 "$tls/server.key"
  echo "    issued"
else
  echo "    exists; kept"
fi

# The HTTPS decoy otherwise generates a fresh certificate on every restart,
# and a certificate that keeps changing is itself a tell.
decoy_tls="$STATE/decoy-tls"
if [[ ! -f "$decoy_tls/server.key" ]]; then
  install -d -m 0755 "$decoy_tls"
  # A different plausible name per install: one CN on every deployment of
  # this project would let them be grouped from a certificate scan.
  decoy_cn=$(printf '%s\n' web01 web-prod-02 app-node-1 srv-web-03 edge-01 www2 portal-01 | shuf -n1)
  openssl req -x509 -newkey rsa:2048 -nodes -days 1095 -sha256 \
    -subj "/CN=${decoy_cn}" -addext "subjectAltName=DNS:${decoy_cn}" \
    -keyout "$decoy_tls/server.key" -out "$decoy_tls/server.crt" 2>/dev/null
  # uid 10001 is the engine's user in honeypot/Dockerfile.
  chown 10001:10001 "$decoy_tls/server.key" "$decoy_tls/server.crt"
  chmod 0600 "$decoy_tls/server.key"
  echo "    issued the HTTPS decoy's certificate"
fi

echo "==> 3/7  GeoIP database (DB-IP City Lite, CC BY 4.0)"
geo="$STATE/geoip"
install -d -m 0755 "$geo"
if [[ ! -f "$geo/city.mmdb" ]] || [[ $(find "$geo/city.mmdb" -mtime +35 | wc -l) -gt 0 ]]; then
  ok=0
  # Published monthly; fall back a month in case this one is not out yet.
  for month in "$(date +%Y-%m)" "$(date -d '-1 month' +%Y-%m)"; do
    if curl -fsSL -m 300 "https://download.db-ip.com/free/dbip-city-lite-${month}.mmdb.gz" \
        -o "$geo/city.mmdb.gz.part"; then
      gunzip -c "$geo/city.mmdb.gz.part" > "$geo/city.mmdb.part"
      mv "$geo/city.mmdb.part" "$geo/city.mmdb"
      rm -f "$geo/city.mmdb.gz.part"
      chmod 0644 "$geo/city.mmdb"
      echo "    installed dbip-city-lite-${month}"
      ok=1
      break
    fi
  done
  [[ $ok -eq 1 ]] || echo "    download failed; sessions will have no location until it succeeds"
else
  echo "    current; kept"
fi

echo "==> 4/7  Egress firewall and backups"
install -m 0644 "$HERE/systemd/"honeysentinel-*.service "$HERE/systemd/"honeysentinel-*.timer /etc/systemd/system/
# Docker refuses to start without the egress rules (fail closed).
install -d -m 0755 /etc/systemd/system/docker.service.d
install -m 0644 "$HERE/systemd/docker.service.d-honeysentinel.conf" /etc/systemd/system/docker.service.d/honeysentinel.conf
systemctl daemon-reload
systemctl enable honeysentinel-egress.service >/dev/null 2>&1
systemctl restart honeysentinel-egress.service
systemctl enable --now honeysentinel-backup.timer >/dev/null 2>&1
iptables -S DOCKER-USER | grep -q HS-DECOY-EGRESS \
  || { echo "    egress rules missing; refusing to expose the engine" >&2; exit 1; }
echo "    egress rules active; nightly backup scheduled"

echo "==> 4b/7  Analysis model"
models="$STATE/models"
install -d -m 0755 "$models"
if [[ -f "$models/$MODEL_FILE" ]]; then
  grep -q '^COMPOSE_PROFILES=' "$ENV_FILE" || echo "COMPOSE_PROFILES=llm" >> "$ENV_FILE"
  grep -q '^CHIMERA_URL=' "$ENV_FILE" || echo "CHIMERA_URL=http://wolfram:8080/v1" >> "$ENV_FILE"
  grep -q '^CHIMERA_MODEL=' "$ENV_FILE" || echo "CHIMERA_MODEL=wolfram" >> "$ENV_FILE"
  echo "    $MODEL_FILE present; the wolfram service and the LLM stage are enabled"
else
  echo "    no $models/$MODEL_FILE; the LLM stage stays off (copy the GGUF there and re-run)"
fi
if [[ -f "$models/$DECIDER_FILE" ]]; then
  grep -q '^COMPOSE_PROFILES=' "$ENV_FILE" || echo "COMPOSE_PROFILES=llm" >> "$ENV_FILE"
  grep -q '^DECIDER_URL=' "$ENV_FILE" || echo "DECIDER_URL=http://decider:8080" >> "$ENV_FILE"
  echo "    $DECIDER_FILE present; the decider service and triage are enabled"
else
  echo "    no $models/$DECIDER_FILE; triage stays off (bash deploy/server/fetch-decider.sh, then re-run)"
fi
# Only when docker-compose.override.yml puts an application behind the decoys.
if docker compose config --services | grep -x shop >/dev/null; then
  systemctl enable --now honeysentinel-shop-reset.timer >/dev/null 2>&1
  echo "    nightly shop reset scheduled"
else
  systemctl disable --now honeysentinel-shop-reset.timer >/dev/null 2>&1 || true
fi

echo "==> 5/7  Build and start"
# A backup before an update, so a bad migration has something to go back to.
if docker compose ps -q postgres 2>/dev/null | grep -q .; then
  bash "$HERE/backup.sh" || echo "    pre-update backup failed; continuing" >&2
fi
docker compose build --pull
docker compose up -d --remove-orphans
docker image prune -f >/dev/null 2>&1 || true

wait_healthy() {
  local service=$1 tries=${2:-90} status=""
  for _ in $(seq 1 "$tries"); do
    status=$(docker inspect -f '{{.State.Health.Status}}' "$(docker compose ps -q "$service")" 2>/dev/null || true)
    [[ "$status" == healthy ]] && return 0
    sleep 2
  done
  echo "    $service did not become healthy" >&2
  docker compose logs --tail 50 "$service" >&2
  return 1
}
echo "    waiting for the API"
wait_healthy backend || exit 1
echo "    waiting for the engine"
wait_healthy honeypot 60 || exit 1

echo "==> 6/7  Administrator"
creds="$STATE/admin-credentials"
if [[ ! -f "$creds" ]]; then
  admin_email=admin@honeysentinel.io
  admin_pass=$(python3 -c "import secrets; print(secrets.token_urlsafe(18))")
  docker compose exec -T -e ADMIN_EMAIL="$admin_email" -e ADMIN_PASSWORD="$admin_pass" \
    backend python - < "$HERE/create_admin.py"
  umask 077
  printf 'email=%s\npassword=%s\n' "$admin_email" "$admin_pass" > "$creds"
  echo "    credentials saved to $creds (root only)"
else
  echo "    exists; kept ($creds)"
fi

echo "==> 7/7  Tailscale Serve"
if tailscale serve status 2>/dev/null | grep -q "127.0.0.1:${WEB_PORT}"; then
  echo "    already serving; left as is"
elif timeout 20 tailscale serve --bg --https=443 "http://127.0.0.1:${WEB_PORT}"; then
  echo "    dashboard: $(grep ^DASHBOARD_ORIGIN "$ENV_FILE" | cut -d= -f2)"
else
  echo "    Serve is not enabled on the tailnet yet: approve the link above, then re-run."
fi

docker compose ps
